version: '3'

services:
  web:
    image: node:22-bookworm-slim
    ports:
      - 3000:3000
      # - 3001:3001
    volumes:
      - .:/www/web/
    command: sh -c "tail -f /dev/null"
    working_dir: /www/web/
    container_name: tiny-slider
    stdin_open: true
    tty: true